### PR TITLE
Remove LLM Functionality from Package

### PR DESCRIPTION
**Pull request by LeonNissen**
# Remove LLM Functionality from Package

## :recycle: Current situation & Problem
Remove the LLM summary and interpretation logic from this package, as it uses application-specific functionality that does not belong within the package

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by LeonNissen** [comment]
We've decided to remove the LLM functionality from `SpeziFHIR` and move it over to the application.

@philippzagar I saw your changes in https://github.com/StanfordSpezi/SpeziFHIR/pull/23. I have transferred them over into `LLMonFHIR` in: https://github.com/StanfordBDHG/LLMonFHIR/pull/53

Feel free to review this pull request, however, it should only remove "application logic" 💯

**Comment by philippzagar** [comment]
@LeonNissen Like with the SpeziChat PR, the commits aren’t properly signed, which might cause a problem later on when we try to merge them.

How do we plan to support applications that depend on SpeziFHIR and the current `SpeziFHIRLLM` target functionality, such as LLMonFHIR and OwnYourData? Probably you and @PSchmiedmayer already have a plan there? Maybe a separate SPM package as a whole?

**Review by PSchmiedmayer — APPROVED** [review]
@philippzagar We discussed it and there will be a need for a dedicated module & package for that type of functionality in the long run. The placement in SpeziFHIR is not ideal and as we move to tagging a 1.0 for this package we need to further define its scope & focus. For now, removing the LLM parts will help us to clean things up. The elements are better positioned in the relevant apps or a dedicated package.

**Comment by philippzagar** [comment]
@PSchmiedmayer 100% agree, the SpeziFHIRLLM target was always intended as a kind of dumping ground for all FHIR-related LLM functionality, therefore less than ideal. 
Great to see that improve 🚀

**Pull request merged**
